### ISSUE TITLE
fatal: Couldn't find remote ref gh-pages

### ISSUE THREAD

**Issue by JamesPJ** [DavidS/jekyll-deploy#3]
My deployment workflow is failing with below error. 

```
Initialized empty Git repository in /github/workspace/_site/.git/
fatal: Couldn't find remote ref gh-pages
/entrypoint.rb:7:in `exit': no implicit conversion from nil to integer (TypeError)
	from /entrypoint.rb:7:in `system_or_fail'
	from /entrypoint.rb:28:in `<main>'
```

I couldn't find the cause.

**Comment by JamesPJ** [comment]
Ok, it was because I didn't had `gh-pages` branch itself. After creating branch, it worked fine but got below error.

`{"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}`

**Comment by JamesPJ** [comment]
After adding repo secrete deployment worked fine.
